project:
  type: book
  output-dir: docs

book:
  title: "Données des aires protégées à Madagascar"
  author: "Florent Bédécarrats, Seheno Ramanantsoa, Ollier D. Andrianambinina"
  date: "09/12/2024"
  repo-url: https://github.com/BETSAKA/conservation-dynamic-madagascar
  license: "CC-BY 4.0"
  chapters:
    - index.qmd
    - 01_sapm_data.qmd
    - 02_wdpa_data.qmd
    - 03_legal_docs.qmd
    - 04_combination.qmd
    - 05_visual_verif.qmd
    - 06_subdivisions.qmd
    - 07_curation.qmd
    - 08_technical_proposal_en.qmd
    - 09_technical_proposal_fr.qmd
    - 10_references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true

execute:
  warning: false
  error: false
